name: "publish"

on:
    workflow_dispatch:
    push:
        branches:
            - main
        tags:
            - "v*"

jobs:
    publish-tauri:
        permissions:
            contents: write
        strategy:
            fail-fast: false
            matrix:
                include:
                    - platform: "windows-latest"
                      args: ""

        runs-on: ${{ matrix.platform }}
        steps:
            - uses: actions/checkout@v4

            - name: Install pnpm
              run: npm install -g pnpm

            - name: Install dependencies (Ubuntu only)
              if: ${{ matrix.platform == 'ubuntu-22.04' }}
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "lts/*"
                  cache: "pnpm"

            - name: Install Rust stable
              uses: dtolnay/rust-toolchain@stable
              with:
                  targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

            - name: Rust cache
              uses: swatinem/rust-cache@v2
              with:
                  workspaces: "./src-tauri -> target"

            - name: Install frontend dependencies
              run: pnpm install

            - name: Build and publish
              uses: tauri-apps/tauri-action@v0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
              with:
                  tagName: app-v__VERSION__
                  releaseName: "App v__VERSION__"
                  releaseBody: "See the assets to download this version and install."
                  releaseDraft: true
                  prerelease: false
                  args: ${{ matrix.args }}

    release:
        name: Release pushed tag
        runs-on: ubuntu-22.04
        steps:
            - name: Create release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  tag: ${{ github.ref_name }}
              run: |
                  gh release create "$tag" \
                      --repo="$GITHUB_REPOSITORY" \
                      --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
                      --generate-notes
